#!/bin/sh

set -e

#VARS
DEFAULT_DISCOVER_AUTOSTART="/etc/xdg/autostart/org.kde.discover.notifier.desktop"
LLX_DISCOVER_AUTOSTART_DIVERSION="/etc/xdg/autostart/org.kde.discover.notifier.desktop.diverted"


PACKAGE_NAME="lliurex-disable-discover-indicator"

case "$1" in
   configure)
		if ! [ -f $LLX_DISCOVER_AUTOSTART_DIVERSION ];then
			dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${LLX_DISCOVER_AUTOSTART_DIVERSION} ${DEFAULT_DISCOVER_AUTOSTART} || true
		fi	
   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#
