#!/bin/sh
set -e

#VARS
DEFAULT_DISCOVER_METADATA_FILE="/usr/share/plasma/plasmoids/org.kde.discovernotifier/metadata.desktop"
DISCOVER_METADATA_FILE_LLIUREX="/usr/share/lliurex-disable-discover-indicator/llx-discovernotifier-metadata.desktop"
PACKAGE_NAME="lliurex-disable-discover-indicator"

case $1 in 
        remove|purge|abort-install|disappear)
                if [ -f ${DEFAULT_DISCOVER_METADATA_FILE}.diverted ] ; then
                        rm -f ${DEFAULT_DISCOVER_METADATA_FILE}
  					    dpkg-divert --package  ${PACKAGE_NAME} --rename --quiet --remove ${DEFAULT_DISCOVER_METADATA_FILE}|| true
                fi
		
		             
                ;;
        *)
                echo "Nothing to do"
                ;; 
esac

