#!/bin/sh
set -e

#VARS
PACKAGE_NAME="lliurex-disable-discover-indicator"
DEFAULT_DISCOVER_AUTOSTART="/etc/xdg/autostart/org.kde.discover.notifier.desktop"


case $1 in 
        remove|purge|abort-install|disappear)
               
                if [ -f ${DEFAULT_DISCOVER_AUTOSTART}.diverted ] ; then
                       rm -f ${DEFAULT_DISCOVER_AUTOSTART}
                       dpkg-divert --package  ${PACKAGE_NAME} --rename --quiet --remove ${DEFAULT_DISCOVER_AUTOSTART}|| true
                fi        
		             
                ;;
        *)
                echo "Nothing to do"
                ;; 
esac

